spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    #baseUrl: http://20.85.43.136:9411
    baseUrl: http://10.0.192.87:9411
    #baseUrl: http://tracing-server:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      #defaultZone: http://20.85.43.136:8761/eureka/
      defaultZone: http://10.0.124.232:8761/eureka/
      #defaultZone: http://discovery-server:8761/eureka/
